insert into Categoria (id, descricao) values (1, 'Eletrônicos');
insert into Categoria (id, descricao, categoria_pai) values (2, 'TVs', 1);
insert into Categoria (id, descricao, categoria_pai) values (3, 'Computadores', 1);
insert into Categoria (id, descricao, categoria_pai) values (4, 'Celulares', 1);
insert into Categoria (id, descricao) values (5, 'Livros');
insert into Categoria (id, descricao, categoria_pai) values (6, 'Romance', 5);
insert into Categoria (id, descricao, categoria_pai) values (7, 'Informática', 5);
insert into Categoria (id, descricao, categoria_pai) values (8, 'Programação', 7);
insert into Categoria (id, descricao, categoria_pai) values (9, 'Java', 8);
insert into Categoria (id, descricao, categoria_pai) values (10, 'Python', 8);
insert into Categoria (id, descricao, categoria_pai) values (11, 'Ruby', 8);
insert into Categoria (id, descricao, categoria_pai) values (12, 'JavaScript', 8);
insert into Categoria (id, descricao, categoria_pai) values (13, 'Redes', 7);
insert into Categoria (id, descricao, categoria_pai) values (14, 'Sistemas Operacionais', 7);
insert into Categoria (id, descricao, categoria_pai) values (15, 'Linux', 14);
insert into Categoria (id, descricao, categoria_pai) values (16, 'Windows', 14);
insert into Categoria (id, descricao, categoria_pai) values (17, 'MacOS', 14);
insert into Categoria (id, descricao) values (18, 'Jogos');
insert into Categoria (id, descricao, categoria_pai) values (19, 'PS3', 18);
insert into Categoria (id, descricao, categoria_pai) values (20, 'PS4', 18);
insert into Categoria (id, descricao, categoria_pai) values (21, 'Xbox 360', 18);
insert into Categoria (id, descricao, categoria_pai) values (22, 'Xbox One', 18);
insert into Categoria (id, descricao) values (23, 'Moda');
insert into Categoria (id, descricao, categoria_pai) values (24, 'Feminino', 23);
insert into Categoria (id, descricao, categoria_pai) values (25, 'Roupas', 24);
insert into Categoria (id, descricao, categoria_pai) values (26, 'Calçados', 24);
insert into Categoria (id, descricao, categoria_pai) values (27, 'Acessórios', 24);
insert into Categoria (id, descricao, categoria_pai) values (28, 'Brincos', 27);
insert into Categoria (id, descricao, categoria_pai) values (29, 'Anéis', 27);
insert into Categoria (id, descricao, categoria_pai) values (30, 'Colares', 27);
insert into Categoria (id, descricao, categoria_pai) values (31, 'Bolsas', 27);
insert into Categoria (id, descricao, categoria_pai) values (32, 'Cintos', 27);
insert into Categoria (id, descricao, categoria_pai) values (33, 'Masculino', 23);
insert into Categoria (id, descricao, categoria_pai) values (34, 'Roupas', 33);
insert into Categoria (id, descricao, categoria_pai) values (35, 'Calçados', 33);
insert into Categoria (id, descricao, categoria_pai) values (36, 'Acessórios', 33);